---
# --- indicates it is a yml
name: Checks

# trigger for this action
on: [push]

# runs-on: where will the github action run?
# uses: we're using existing action defined on github actions. can also define custom actions for this
# ubuntu-20.04: comes with docker installed
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_USER }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"